[app]
mode = "develop"
name = "yunju"
level = "debug"
#随机生成随机字符串
secret = "y66F6cW$u^BSeH!%yRSHNP!2gwovkOnq"
port = 9000
unAuthUrl = ["/login", "/upload"]


[mysql]
driver = "mysql"
dsn = "root:zhaoshuai123@tcp(127.0.0.1:3306)/yunju?charset=utf8&parseTime=True&loc=Local&interpolateParams=true"
maxIdleConn = 8
maxOpenConn = 16
maxLifetime = 600

[zap]
file = "./yunju-http.log"
maxSize = 10 # 日志文件大小 M
maxAge = 3  # 最多保存多少备份
maxBackups = 10 # 保存多少天
compress = true
